---
title: "Eric_MPA_Final_Markdown"
author: "Eric Newton"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(scales)
library(cowplot)
library(mapview)
here()

mytheme <- theme_classic(base_size = 14)+
  theme(legend.background = element_rect(
    color = "grey",
    fill = "white"),
    plot.title = element_text(hjust = 0.5, size = 12),
    legend.position = "bottom",
    panel.grid.major = element_line(color = "grey", linetype = "dashed"))
   
    
theme_set(mytheme)
  
MPA.data <- read.csv(here('DataRaw/NOAA_Marine_Protected_Areas_Inventory_2023.csv'),
                     stringsAsFactors = TRUE, 
                     colClasses = c('Year.Established' = 'factor'))

MPA.data.clean <- MPA.data %>%
  select(OBJECTID, Site.Name, State, Level.of.Protection, Management.Plan, Year.Established, Marine.Status, Area..km2., Marine.Area..km2., Percent.Area.Marine, No.Take.Area..km2., Longitude, Latitude) %>% 
  filter(Year.Established != 0)

MPA.data.clean$Year.Established <- as.Date(MPA.data.clean$Year.Established, format = '%Y')

colnames(MPA.data.clean)[8] <- "Area"
colnames(MPA.data.clean)[9] <- "Marine.Area"
colnames(MPA.data.clean)[11] <- "No.Take.Area"



#Clean.plot <- 
  ggplot(MPA.data.clean) +
  geom_bar(aes(x=Year.Established)) +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y", limits = as.Date(c("2000-11-15", "2023-11-15"))) +
  labs(x = "Year", y = "Count")
#print(Clean.plot)




```

## R Markdown



```{r, Level of Protection DFs}


Zoned.w.No.Take.Areas.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "Zoned w/No Take Areas") %>% 
  mutate("Cum.Area" = cumsum(Area))

Uniform.Multiple.Use.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "Uniform Multiple Use") %>% 
  mutate("Cum.Area" = cumsum(Area))


No.Take.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "No Take") %>% 
  mutate("Cum.Area" = cumsum(Area))

Zoned.Multiple.Use.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "Zoned Multiple Use") %>% 
  mutate("Cum.Area" = cumsum(Area))
  
No.Access.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "No Access") %>% 
  mutate("Cum.Area" = cumsum(Area))

No.Impact.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Level.of.Protection == "No Impact") %>% 
  mutate("Cum.Area" = cumsum(Area))

Combined.Cumulative.Level.of.Protection <- rbind(
  Zoned.w.No.Take.Areas.df,
  Uniform.Multiple.Use.df,
  No.Take.df,
  Zoned.Multiple.Use.df,
  No.Access.df,
  No.Impact.df)
  

```

```{r Level of Protection Plots}

Zoned.w.No.Take.Areas.plot <- 
  ggplot(Zoned.w.No.Take.Areas.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "Zoned with No Take Areas",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(Zoned.w.No.Take.Areas.plot)

Uniform.Multiple.Use.plot <- 
  ggplot(Uniform.Multiple.Use.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "Uniform Multiple Use",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(Uniform.Multiple.Use.plot)

No.Take.plot <- 
  ggplot(No.Take.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "No Take",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(No.Take.plot)

Zoned.Multiple.Use.plot <- 
  ggplot(Zoned.Multiple.Use.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "Zoned Multiple Use",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(Zoned.Multiple.Use.plot)

No.Access.plot <- 
  ggplot(No.Access.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "No Access",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(No.Access.plot)

No.Impact.plot <-
  ggplot(No.Impact.df) +
  geom_line(aes(
    x = year,
    y = Cum.Area)) +
  labs(
    title = "No Impact",
    x = "Time",
    y = "Area (million km^2)") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
  print(No.Impact.plot)

Combined.plot.LoP <-
  ggplot(Combined.Cumulative.Level.of.Protection) +
  geom_line(aes(
    x = year,
    y = Cum.Area,
    color = Level.of.Protection),
    size = 1.5) +
  labs(
    title = "Cumulative Area of MPAs over Time by Level of Protection",
    x = "Time",
    y = "Cumulative Area (km)") +
  scale_y_continuous(labels = scales::comma)
  print(Combined.plot.LoP)

Combined.no.Zoned.w.No.Take <-
  ggplot(Combined.Cumulative.Level.of.Protection %>% 
    filter(Level.of.Protection != "Zoned w/No Take Areas")) +
  geom_line(aes(
    x = year,
    y = Cum.Area,
    color = Level.of.Protection),
    size = 1) +
  labs(
    title = "Cumulative Area of MPAs over Time by Level of Protection\n excluding 'Zoned with No Take Areas'",
    x = "Time",
    y = "Cumulative Area (km)") +
  scale_y_continuous(labels = scales::comma)
  print(Combined.no.Zoned.w.No.Take)
  
LevelofProtection.Count <- ggplot(MPA.data.clean) +
  geom_bar(aes(x=Level.of.Protection)) +
  labs(x = "Level of Protection",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 90))
#print(LevelofProtection)

LevelofProtection.Area <- ggplot(MPA.data.clean) +
  geom_col(aes(
    x = Level.of.Protection,
    y = Area)) +
  labs(x = "Level of Protection",
       y = "Total Area") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6))
#print(LevelofProtection.Area)

  
```

## Including Plots

You can also embed plots, for example:


```{r Level of Protection Spatial Analysis}

#spatial_db <- sf::st_read(here('DataRaw/NOAA_MPAI_2023.gdb'))



#LoP.map <- 
  #mapview(spatial_db, zcol = 'Prot_Lvl')
#print(LoP.map)

```



```{r Management Plan dfs}

Species.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "Non-MPA Programmatic Species Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

Site.Specific.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "Site-Specific Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

No.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "No Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

Habitat.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "Non-MPA Programmatic Habitat Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

MPA.Programmatic.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "MPA Programmatic Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

Fisheries.Management.Plan.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "MPA Programmatic Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

Community.Agreement.df <- MPA.data.clean %>% 
  mutate("year" = year(Year.Established)) %>%
  arrange(ymd(MPA.data.clean$Year.Established)) %>% 
  filter(Management.Plan == "MPA Programmatic Management Plan") %>% 
  mutate("Cum.Area" = cumsum(Area))

Combined.Cumulative.Management.Plan <- rbind(
  Species.Management.Plan.df,
  Site.Specific.Management.Plan.df,
  No.Management.Plan.df,
  Habitat.Management.Plan.df,
  MPA.Programmatic.Management.Plan.df,
  Fisheries.Management.Plan.df,
  Community.Agreement.df)

```

```{r Management Plan plots}

Combined.Management.Plan.plot <-
  ggplot(Combined.Cumulative.Management.Plan) +
  geom_line(aes(
    x = year,
    y = Cum.Area,
    color = Management.Plan),
    size = 1.5) +
  labs(
    title = "Cumulative Area of MPAs over Time by Management Plan",
    x = "Time",
    y = "Cumulative Area (km)") +
  scale_y_continuous(labels = scales::comma)
  print(Combined.Management.Plan.plot)

Combined.no.Site.Specific <-
  ggplot(Combined.Cumulative.Level.of.Protection %>% 
    filter(Level.of.Protection != "Site-Specific Management Plan")) +
  geom_line(aes(
    x = year,
    y = Cum.Area,
    color = Level.of.Protection),
    size = 1) +
  labs(
    title = "Cumulative Area of MPAs over Time by Management Plan\n excluding 'Site-Specific Management Plan'",
    x = "Time",
    y = "Cumulative Area (km)") +
  scale_y_continuous(labels = scales::comma)
  print(Combined.no.Site.Specific)
  
Management.Plan.Count <- ggplot(MPA.data.clean) +
  geom_bar(aes(x=Management.Plan)) +
  labs(x = "Management Plan Type",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 90))
print(Management.Plan.Count)

Management.Plan.Area <- ggplot(MPA.data.clean) +
  geom_col(aes(
    x = Management.Plan,
    y = Area)) +
  labs(x = "Management Plan",
       y = "Total Area (million km^2)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(labels = scales::number_format(scale = 1e-4))
print(Management.Plan.Area)

```

