---
title: "Final Project"
author: "Justin Maynard"
date: '`r Sys.Date()`'
output: html_document
runtime: shiny
---


```{r, echo=FALSE}
library(shiny)
library(leaflet)
library(RColorBrewer)
library(here)
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(sf)
library(shiny)
library(leaflet)
library(RColorBrewer)
library(mapview); mapviewOptions(fgb = FALSE)
sf::sf_use_s2(FALSE)

here()

MPA.data <- read.csv(here('DataRaw/NOAA_Marine_Protected_Areas_Inventory_2023.csv'),
                     stringsAsFactors = TRUE, 
                     colClasses = c('Year.Established' = 'factor'))

MPA.data.clean <- MPA.data %>%
  select(OBJECTID, Site.Name, State, Level.of.Protection, Management.Plan, Year.Established, Marine.Status, Area..km2., Marine.Area..km2., Percent.Area.Marine, No.Take.Area..km2., Longitude, Latitude) %>% 
  filter(Year.Established != 0)

MPA.data.clean$Year.Established <- as.Date(MPA.data.clean$Year.Established, format = '%Y')

colnames(MPA.data.clean)[8] <- "Area"
colnames(MPA.data.clean)[9] <- "Marine.Area"
colnames(MPA.data.clean)[11] <- "No.Take.Area"
  

MPA.sites.sf <- MPA.data.clean %>% 
  st_as_sf(coords = c("Longitude","Latitude"),
           crs = 4326)

MPA.data.sf <- MPA.data %>% 
  st_as_sf(coords = c("Longitude","Latitude"),
           crs = 4326)


database <- sf::st_read(here('DataRaw/NOAA_MPAI_2023.gdb')) 

database_transformed <- st_transform(database, c=4326)

df1 <- MPA.data.sf %>% 
  select(Site.ID, Level.of.Protection)

joined_data <- st_join(database_transformed, df1, by = "Site.ID")


joined_data_renamed <- joined_data %>% 
  mutate(Regions = recode(State,
                          "AK" = "Alaska",
                          "NC" = "South",
                          "ASM" = "Pacific",
                          "CT" ="Northeast",
                          "DE" = "Northeast",
                          "FL" = "South",
                          "CA" = "West",
                          "GA" = "South",
                          "US-GU" = "Pacific",
                          "HI" = "Pacific",
                          "IL" = "Midwest",
                          "MN" = "Midwest",
                          "US-MP" = "Pacific",
                          "IN" = "Midwest",
                          "LA" = "South",
                          "MA" = "Northeast",
                          "MI" = "Midwest",
                          "MS" = "South",
                          "AL, MS" = "South",
                          "NH" = "Northeast",
                          "NJ" = "Northeast",
                          "OH" = "Midwest",
                          "OR" = "West",
                          "PR" = "Pacific",
                          "TX" = "South",
                          "VA" = "South",
                          "US-VI" = "Pacific",
                          "WA" = "West",
                          "PRI" = "Pacific",
                          "NY" = "Northeast",
                          "PA" = "Northeast",
                          "SC" = "South",
                          "RI" = "Northeast",
                          "ME" = "Northeast",
                          "MD" = "Northeast",
                          "WI" = "Midwest",
                          "FL, MS" = "South",
                          "VA, MD" = "South",
                          "AL" = "South",
                          "OR, WA" = "West",
                          "NC, VA" = "South",
                          "NJ, NY" = "Northeast",
                          "US-MI, CA-ON" = "Canada",
                          "GA, SC" = "South",
                          "TX, LA" = "South",
                          ))
```

```{r, echo=FALSE}






ui <- fluidPage(
  leafletOutput("map"),
  absolutePanel(bottom = 10, left = 10,
                selectInput("regions", label = "Select region to visualize", choices = unique(joined_data_renamed$Regions), selected = "Northeast"),
                selectInput("filter", 
                            label = "Select way to filter",
                            choices = c("Mgmt_Plan", "Level.of.Protection"))

                  
  )
)
  



server <- function(input, output, session) {
  

  observe({
    
    regionSelection =  input$regions 
    filterSelection = input$filter
    
    m <- mapview(filter(joined_data_renamed, Regions == regionSelection), zcol = filterSelection)
    output$map <- renderLeaflet({
      m@map
    })
  })
   
}

shinyApp(ui, server)


```